window.PA28_MATERIAL = [
  {
    group: "Briefing y emergencias",
    kind: "pdf",
    title: "Briefing de emergencia PA-28 · actualizado",
    description: "Despegue normal, velocidades de referencia y respuesta ante una falla de motor según el briefing más reciente.",
    file: "material/aeroclub-pa28/briefing/briefing-emergencias-pa28-actualizado.pdf",
  },
  {
    group: "Briefing y emergencias",
    kind: "pdf",
    title: "Briefing de emergencia PA-28",
    description: "Versión anterior del briefing para conservar como referencia y comparar actualizaciones.",
    file: "material/aeroclub-pa28/briefing/briefing-emergencias-pa28.pdf",
  },
  {
    group: "Briefing y emergencias",
    kind: "pdf",
    title: "Checklist de emergencias PA-28",
    description: "Procedimientos de fuego, fallas de motor y sistemas, aterrizaje sin potencia, barrena y puerta abierta.",
    file: "material/aeroclub-pa28/checklists/checklist-emergencias-pa28.pdf",
  },
  {
    group: "Checklists de operación",
    kind: "pdf",
    title: "Checklist PA-28 LV-LLS",
    description: "Lista completa desde preparación de cabina e inspección exterior hasta parada de motor.",
    file: "material/aeroclub-pa28/checklists/checklist-pa28-lv-lls.pdf",
  },
  {
    group: "Checklists de operación",
    kind: "pdf",
    title: "Lista de chequeo PA-28 · compacta",
    description: "Versión compacta de la lista de chequeo del LV-LLS.",
    file: "material/aeroclub-pa28/checklists/lista-chequeo-pa28-compacta.pdf",
  },
  {
    group: "Checklists de operación",
    kind: "pdf",
    title: "Lista de chequeo PA-28",
    description: "Copia equivalente de la versión compacta recibida.",
    file: "material/aeroclub-pa28/checklists/lista-chequeo-pa28.pdf",
  },
  {
    group: "Operaciones y vuelos",
    kind: "pdf",
    private: true,
    title: "Plan de vuelo LV-LLS · SANL 13:00",
    description: "Plan de vuelo del 28/08/26 para consulta interna.",
    file: "material/aeroclub-pa28/operaciones/plan-vuelo-lvlls-sanl-1300-280826.pdf",
  },
  {
    group: "Operaciones y vuelos",
    kind: "pdf",
    private: true,
    title: "Plan de vuelo LV-LLS · SANL 18:30",
    description: "Plan de vuelo del 28/08/26 para consulta interna.",
    file: "material/aeroclub-pa28/operaciones/plan-vuelo-lvlls-sanl-1830-280826.pdf",
  },
  {
    group: "Referencias rápidas",
    kind: "pdf",
    title: "Tabla de conversión · Aeroclub La Rioja",
    description: "Tabla recibida en formato de referencia del aeroclub.",
    file: "material/aeroclub-pa28/referencias/tabla-conversion-aeroclub-la-rioja.pdf",
  },
  {
    group: "Referencias rápidas",
    kind: "pdf",
    title: "Tabla de conversión hPa / inHg",
    description: "Conversión de presión atmosférica entre hPa e inHg.",
    file: "material/aeroclub-pa28/referencias/tabla-conversion-aeroclub.pdf",
  },
  {
    group: "Referencias rápidas",
    kind: "image",
    title: "Códigos transponder ICE",
    description: "Ayuda visual: 7500 interferencia ilícita, 7600 pérdida de comunicaciones y 7700 emergencia.",
    file: "material/aeroclub-pa28/imagenes/codigos-transponder-ice.jpg",
    image: "material/aeroclub-pa28/imagenes/codigos-transponder-ice.jpg",
  },
  {
    group: "Referencias rápidas",
    kind: "image",
    title: "Canales aeronáuticos de emergencia",
    description: "Ayuda visual con 121,5 MHz y 243,0 MHz. Confirmar siempre la frecuencia aplicable con ATC/instructor.",
    file: "material/aeroclub-pa28/imagenes/canales-emergencia.jpg",
    image: "material/aeroclub-pa28/imagenes/canales-emergencia.jpg",
  },
  {
    group: "Referencias rápidas",
    kind: "image",
    title: "Tabla hPa / inHg · imagen",
    description: "Recorte visual de la tabla de conversión recibida.",
    file: "material/aeroclub-pa28/imagenes/tabla-hpa-inhg.jpg",
    image: "material/aeroclub-pa28/imagenes/tabla-hpa-inhg.jpg",
  },
];

window.PA28_REVIEW_QUESTIONS = [
  {
    topic: "normal",
    question: "En la preparación de cabina, ¿cómo debe estar el calefactor del carburador?",
    options: ["Aire frío", "Aire caliente", "A requerimiento"],
    correct: 0,
    explanation: "La lista de chequeo indica aire frío durante la preparación de cabina.",
    source: "Checklist PA-28 LV-LLS",
  },
  {
    topic: "normal",
    question: "En la preparación de cabina, ¿cómo debe quedar la mezcla?",
    options: ["Rica", "Cortada", "Ajustada para crucero"],
    correct: 1,
    explanation: "La lista de chequeo indica mezcla cortada en esta etapa.",
    source: "Checklist PA-28 LV-LLS",
  },
  {
    topic: "normal",
    question: "Antes de la puesta en marcha, ¿qué se hace con los flaps?",
    options: ["Retraerlos", "Desplegarlos a full", "Dejarlos a requerimiento"],
    correct: 0,
    explanation: "Antes de la puesta en marcha, la checklist indica retraer los flaps.",
    source: "Checklist PA-28 LV-LLS",
  },
  {
    topic: "normal",
    question: "Sin torre de control, durante la puesta en marcha la potencia se avanza a:",
    options: ["Ralentí", "1/4", "2000 RPM"],
    correct: 1,
    explanation: "La secuencia de puesta en marcha indica avanzar la potencia a 1/4.",
    source: "Checklist PA-28 LV-LLS",
  },
  {
    topic: "normal",
    question: "Si no hay presión de aceite dentro de los 30 segundos posteriores al arranque, se debe:",
    options: ["Aumentar a 2000 RPM", "Parar el motor", "Conectar la bomba eléctrica"],
    correct: 1,
    explanation: "La checklist indica parar el motor si no aparece presión de aceite dentro de 30 segundos.",
    source: "Checklist PA-28 LV-LLS",
  },
  {
    topic: "normal",
    question: "Durante la prueba de motor en tierra, la potencia se ajusta a:",
    options: ["1000 RPM", "2000 RPM", "2300/2400 RPM"],
    correct: 1,
    explanation: "La prueba de motor en tierra se realiza a 2000 RPM.",
    source: "Checklist PA-28 LV-LLS",
  },
  {
    topic: "normal",
    question: "¿Cuál es la caída máxima indicada para cada magneto durante la prueba de motor?",
    options: ["50 RPM", "175 RPM", "250 RPM"],
    correct: 1,
    explanation: "La lista indica una caída máxima de 175 RPM y una diferencia máxima entre ambos de 50 RPM.",
    source: "Checklist PA-28 LV-LLS",
  },
  {
    topic: "normal",
    question: "¿Cuál es la diferencia máxima indicada entre ambos magnetos?",
    options: ["25 RPM", "50 RPM", "175 RPM"],
    correct: 1,
    explanation: "La checklist indica una diferencia máxima entre ambos de 50 RPM.",
    source: "Checklist PA-28 LV-LLS",
  },
  {
    topic: "normal",
    question: "Durante la prueba de motor, el medidor de succión debe indicar entre:",
    options: ["1 y 2 HG", "4 y 6 HG", "8 y 10 HG"],
    correct: 1,
    explanation: "La checklist indica chequear la succión entre 4 y 6 HG.",
    source: "Checklist PA-28 LV-LLS",
  },
  {
    topic: "normal",
    question: "Antes del despegue, la bomba eléctrica de combustible debe estar:",
    options: ["Off", "Conectada (ON)", "A requerimiento solamente después de rotar"],
    correct: 1,
    explanation: "La lista de chequeo indica conectar la bomba eléctrica antes del despegue.",
    source: "Checklist PA-28 LV-LLS",
  },
  {
    topic: "normal",
    question: "Según la checklist, la velocidad de rotación indicada es:",
    options: ["60/65 Kts", "65/70 Kts", "80 Kts"],
    correct: 1,
    explanation: "La checklist indica 65/70 Kts para la rotación; el briefing actualizado expresa VR como 60-65 Kts. Confirmar la versión vigente con el instructor.",
    source: "Checklist PA-28 LV-LLS y briefing actualizado",
  },
  {
    topic: "normal",
    question: "La velocidad de ascenso normal indicada en la checklist es:",
    options: ["65/70 Kts", "75 Kts", "80 Kts"],
    correct: 2,
    explanation: "La checklist indica 80 Kts para el ascenso normal.",
    source: "Checklist PA-28 LV-LLS",
  },
  {
    topic: "normal",
    question: "En crucero, la potencia indicada es:",
    options: ["1100 RPM", "2000 RPM", "2300/2400 RPM"],
    correct: 2,
    explanation: "La checklist indica ajustar 2300/2400 RPM en crucero.",
    source: "Checklist PA-28 LV-LLS",
  },
  {
    topic: "normal",
    question: "Durante el descenso, el altímetro se ajusta a:",
    options: ["QNH", "Cero", "La presión de aceite"],
    correct: 0,
    explanation: "La checklist indica ajustar el altímetro a QNH durante el descenso.",
    source: "Checklist PA-28 LV-LLS",
  },
  {
    topic: "normal",
    question: "Antes del aterrizaje, se selecciona el tanque de combustible de:",
    options: ["Menor cantidad", "Mayor cantidad", "Reserva fija"],
    correct: 1,
    explanation: "La checklist indica seleccionar el tanque de mayor cantidad.",
    source: "Checklist PA-28 LV-LLS",
  },
  {
    topic: "normal",
    question: "Después del aterrizaje, el transponder se coloca en:",
    options: ["ALT", "IDENT", "Standby"],
    correct: 2,
    explanation: "La checklist indica colocar el transponder en Standby después del aterrizaje.",
    source: "Checklist PA-28 LV-LLS",
  },
  {
    topic: "normal",
    question: "Durante la parada de motor, la potencia se lleva a:",
    options: ["1100 RPM", "2000 RPM", "Máxima RPM"],
    correct: 0,
    explanation: "La checklist indica 1100 RPM antes de cortar la mezcla.",
    source: "Checklist PA-28 LV-LLS",
  },
  {
    topic: "emergency",
    question: "Ante fuego en el motor durante la puesta en marcha, el selector de tanque debe:",
    options: ["Abrirse en el tanque de mayor cantidad", "Cerrarse", "Quedar a requerimiento"],
    correct: 1,
    explanation: "La checklist de emergencias indica cerrar el selector de tanque.",
    source: "Checklist de emergencias PA-28",
  },
  {
    topic: "emergency",
    question: "Ante una falla de motor durante el despegue sin pista remanente, se mantiene:",
    options: ["76 Kts y virajes suaves, máximo 20°", "90 Kts y un viraje de 180° inmediato", "100 Kts y máximo banqueo"],
    correct: 0,
    explanation: "El procedimiento indica mantener 76 Kts y virajes suaves con máximo 20° cuando no hay pista remanente.",
    source: "Checklist de emergencias PA-28",
  },
  {
    topic: "emergency",
    question: "Ante una falla de motor en vuelo, la mezcla se coloca:",
    options: ["Cortada", "Rica", "Ajustada a crucero"],
    correct: 1,
    explanation: "La secuencia de falla de motor en vuelo indica mezcla rica.",
    source: "Checklist de emergencias PA-28",
  },
  {
    topic: "emergency",
    question: "Si no existe presión de combustible, se verifica que el selector esté abierto en el tanque de:",
    options: ["Menor cantidad", "Mayor cantidad", "Reserva"],
    correct: 1,
    explanation: "La checklist indica verificar el tanque abierto de mayor cantidad.",
    source: "Checklist de emergencias PA-28",
  },
  {
    topic: "emergency",
    question: "Ante fuego de motor en vuelo, el calefactor del carburador se coloca en:",
    options: ["Aire frío", "Aire caliente", "A requerimiento"],
    correct: 0,
    explanation: "El procedimiento de fuego de motor en vuelo indica aire frío.",
    source: "Checklist de emergencias PA-28",
  },
  {
    topic: "emergency",
    question: "Ante fuego eléctrico o humo en cabina, el Master debe colocarse en:",
    options: ["On", "Standby", "Off"],
    correct: 2,
    explanation: "La checklist indica Master Off, alternador Off, venteos abiertos y calefacción cerrada.",
    source: "Checklist de emergencias PA-28",
  },
  {
    topic: "emergency",
    question: "Para un aterrizaje sin potencia, la velocidad de planeo indicada es:",
    options: ["65 Kts", "76 Kts", "90 Kts"],
    correct: 1,
    explanation: "La checklist de emergencias indica 76 Kts como velocidad de planeo.",
    source: "Checklist de emergencias PA-28",
  },
  {
    topic: "emergency",
    question: "Ante pérdida de presión de aceite o alta temperatura de aceite, se indica:",
    options: ["Continuar hasta destino", "Aterrizar tan pronto sea posible e investigar las causas", "Apagar todos los instrumentos y ascender"],
    correct: 1,
    explanation: "Ambos procedimientos indican aterrizar tan pronto sea posible y prepararse para un aterrizaje sin potencia.",
    source: "Checklist de emergencias PA-28",
  },
  {
    topic: "emergency",
    question: "En la recuperación de una barrena, el timón de dirección se aplica:",
    options: ["Todo en el sentido del giro", "Todo en dirección contraria al giro", "Neutral desde el comienzo"],
    correct: 1,
    explanation: "La checklist indica timón todo en dirección contraria al sentido del giro; luego neutral cuando se detenga.",
    source: "Checklist de emergencias PA-28",
  },
  {
    topic: "emergency",
    question: "Si durante la falla eléctrica el amperímetro marca cero, el alternador se debe:",
    options: ["Desconectar", "Conectar y dejarlo así siempre", "Reemplazar por la batería"],
    correct: 0,
    explanation: "El procedimiento indica desconectar el alternador, reducir cargas y verificar/resetear el fusible según corresponda.",
    source: "Checklist de emergencias PA-28",
  },
  {
    topic: "emergency",
    question: "Ante una sobrecarga eléctrica de más de 20 amperes sobre la carga conocida, se indica desconectar la:",
    options: ["Batería", "Luz de aterrizaje", "Bomba de combustible"],
    correct: 0,
    explanation: "La checklist indica conectar el alternador y desconectar la batería, reduciendo cargas al mínimo.",
    source: "Checklist de emergencias PA-28",
  },
  {
    topic: "emergency",
    question: "Para cerrar una puerta abierta en vuelo, la velocidad se reduce a:",
    options: ["76 Kts", "90 Kts", "120 Kts"],
    correct: 1,
    explanation: "El procedimiento indica reducir la velocidad a 90 Kts antes de intentar cerrar la puerta.",
    source: "Checklist de emergencias PA-28",
  },
  {
    topic: "emergency",
    question: "Ante formación de hielo en el carburador, se debe:",
    options: ["Abrir la calefacción del carburador y actuar con máxima suavidad sobre la mezcla", "Cerrar la calefacción y cortar mezcla", "Apagar la batería"],
    correct: 0,
    explanation: "La checklist indica abrir la calefacción del carburador y efectuar la mezcla con máxima suavidad.",
    source: "Checklist de emergencias PA-28",
  },
  {
    topic: "reference",
    question: "El código transponder 7500 se asocia con:",
    options: ["Pérdida de comunicaciones", "Interferencia ilícita", "Emergencia general"],
    correct: 1,
    explanation: "La ayuda visual ICE recibida asocia 7500 con interferencia ilícita.",
    source: "Imagen: Códigos transponder ICE",
  },
  {
    topic: "reference",
    question: "El código transponder 7600 se utiliza para indicar:",
    options: ["Pérdida de comunicaciones", "Interferencia ilícita", "Emergencia en el avión"],
    correct: 0,
    explanation: "La ayuda visual ICE recibida asocia 7600 con pérdida de comunicaciones.",
    source: "Imagen: Códigos transponder ICE",
  },
  {
    topic: "reference",
    question: "El código transponder 7700 se utiliza para indicar:",
    options: ["Pérdida de comunicaciones", "Interferencia ilícita", "Emergencia en el avión"],
    correct: 2,
    explanation: "La ayuda visual ICE recibida asocia 7700 con emergencia en el avión.",
    source: "Imagen: Códigos transponder ICE",
  },
  {
    topic: "reference",
    question: "Según la ayuda visual recibida, la frecuencia civil de emergencia es:",
    options: ["121,5 MHz", "123,5 MHz", "243,0 MHz"],
    correct: 0,
    explanation: "La imagen recibida identifica 121,5 MHz como frecuencia civil de emergencia. Confirmar siempre la frecuencia aplicable con ATC/instructor.",
    source: "Imagen: Canales aeronáuticos de emergencia",
  },
  {
    topic: "reference",
    question: "Según la ayuda visual recibida, la frecuencia militar de emergencia es:",
    options: ["121,5 MHz", "243,0 MHz", "245,0 MHz"],
    correct: 1,
    explanation: "La imagen recibida identifica 243,0 MHz como frecuencia militar de emergencia. Confirmar siempre la frecuencia aplicable con ATC/instructor.",
    source: "Imagen: Canales aeronáuticos de emergencia",
  },
  {
    topic: "reference",
    question: "Según el briefing actualizado, la velocidad óptima de planeo (VL/D) es:",
    options: ["65 Kts", "76 Kts", "80 Kts"],
    correct: 1,
    explanation: "El briefing actualizado indica VL/D: 76 KTS.",
    source: "Briefing de emergencia PA-28 · actualizado",
  },
  {
    topic: "reference",
    question: "Según el briefing actualizado, al alcanzar 500 pies sobre el terreno se desconfigura:",
    options: ["Bomba, luz y flap", "Master, alternador y batería", "Calefactor, mezcla y magnetos"],
    correct: 0,
    explanation: "El briefing indica desconfigurar bomba, luz y flap al alcanzar 500 pies sobre el terreno, con primera reducción de motor.",
    source: "Briefing de emergencia PA-28 · actualizado",
  },
  {
    topic: "reference",
    question: "En la tabla de conversión recibida, 1013 hPa equivalen aproximadamente a:",
    options: ["29,92 inHg", "30,36 inHg", "28,92 inHg"],
    correct: 0,
    explanation: "La tabla hPa/inHg recibida muestra 1013 hPa = 29,92 inHg.",
    source: "Tabla de conversión hPa / inHg",
  },
];
